version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: pii-shield-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "pii_redis_pass", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "pii_redis_pass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: 